#:schema node_modules/wrangler/config-schema.json
name = "proxydocker"
main = "_worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Variable bindings
# Docs: https://developers.cloudflare.com/workers/configuration/environment-variables/
# [vars]
# MY_VARIABLE = "production_value"

# Bind the Workers AI model catalog
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#ai
# [ai]
# binding = "AI"
